name: Build And Release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          npm install terser
          npx terser tiny.js -o tiny.js
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: tiny.js
